linux_task:
  container:
    image: rust:latest
  environment:
    RUSTUP_TOOLCHAIN: stable
    CARGO_MAKE_CI: TRUE
    # CARGO_MAKE_RUN_CODECOV: true
    # CODECOV_TOKEN: ENCRYPTED[753b7c8cdef62fcfd7149044e8a56c47d145122e17da193be80d7c614e9bc4804c5aa98260283aa7e78c9236b7775929]
    TARGET: x86_64-unknown-linux-gnu
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  before_script: cargo install cargo-make || echo "cargo-make already installed"
  display_env_script: rustup -V; rustc -V; cargo -V; cargo make --version
  build_script: cargo make ci-flow
  before_cache_script: rm -rf $CARGO_HOME/registry/index

windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
    install_script: |
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
        set PATH=%PATH%;%USERPROFILE%\.cargo\bin
        echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  environment:
    RUSTUP_TOOLCHAIN: stable
    CARGO_MAKE_CI: TRUE
    # CARGO_MAKE_RUN_CODECOV: true
    # CODECOV_TOKEN: ENCRYPTED[753b7c8cdef62fcfd7149044e8a56c47d145122e17da193be80d7c614e9bc4804c5aa98260283aa7e78c9236b7775929]
    TARGET: TARGET=x86_64-pc-windows-msvc
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  before_script: cargo install cargo-make || echo "cargo-make already installed"
  display_env_script: rustup -V; rustc -V; cargo -V; cargo make --version
  build_script: cargo make ci-flow
  before_cache_script: rm -rf $CARGO_HOME\registry\index

osx_task:
  osx_instance:
    image: mojave-xcode-10.1
    install_script: |
        curl https://sh.rustup.rs -sSf | sh
        rustup -y --default-toolchain $RUSTUP_TOOLCHAIN
        . $HOME/.cargo/env
  environment:
    RUSTUP_TOOLCHAIN: stable
    CARGO_MAKE_CI: TRUE
    # CARGO_MAKE_RUN_CODECOV: true
    # CODECOV_TOKEN: ENCRYPTED[753b7c8cdef62fcfd7149044e8a56c47d145122e17da193be80d7c614e9bc4804c5aa98260283aa7e78c9236b7775929]
    TARGET: x86_64-apple-darwin
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  before_script: cargo install cargo-make || echo "cargo-make already installed"
  display_env_script: rustup -V; rustc -V; cargo -V; cargo make --version
  build_script: cargo make ci-flow
  before_cache_script: rm -rf $CARGO_HOME\registry\index
