container:
  image: rust:latest

test_task:
  environment:
    TARGET: x86_64-unknown-linux-gnu
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  display_env_script: rustup -V; rustc -V; cargo -V; cargo make --version
  build_script: cargo make ci-flow
  before_cache_script: rm -rf $CARGO_HOME/registry/index
