container:
  image: rust:latest

test_task:
  environment:
    TARGET: x86_64-unknown-linux-gnu
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --target $TARGET --release
  test_script: cargo test --target $TARGET --release
  before_cache_script: rm -rf $CARGO_HOME/registry/index
