container:
  image: rust:latest

test_task:
  environment:
    CARGO_MAKE_CI: TRUE
    CARGO_MAKE_RUN_CODECOV: true
    CODECOV_TOKEN: ENCRYPTED[753b7c8cdef62fcfd7149044e8a56c47d145122e17da193be80d7c614e9bc4804c5aa98260283aa7e78c9236b7775929]
    TARGET: x86_64-unknown-linux-gnu
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  before_script: cargo install cargo-make || echo "cargo-make already installed"
  display_env_script: rustup -V; rustc -V; cargo -V; cargo make --version
  build_script: cargo make ci-flow
  before_cache_script: rm -rf $CARGO_HOME/registry/index
