strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
      TARGET: x86_64-apple-darwin
    mac:
      imageName: 'macos-10.13'
      TARGET: x86_64-apple-darwin
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  RUSTUP_TOOLCHAIN: stable
  CARGO_MAKE_CI: TRUE
  # CARGO_MAKE_RUN_CODECOV: true
  # CODECOV_TOKEN: ENCRYPTED[753b7c8cdef62fcfd7149044e8a56c47d145122e17da193be80d7c614e9bc4804c5aa98260283aa7e78c9236b7775929]

steps:
# Linux
- bash: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: install rustup
# macOS
- bash: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: install rustup
# Windows
- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
    set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: install rustup

# All platforms.
- script: |
      cargo install cargo-make || echo "cargo-make already installed"
      rustup -V
      rustc -V
      cargo -V
      cargo make --version
  displayName: Query rust and cargo versions

- script: |
    cargo make ci-flow
  displayName: ci-flow
