[package]
name = "ffizer"
version = "0.1.2"
authors = ["David Bernard"]
description = "ffizer is a files and folders initializer / generator. Create any kind (or part) of project from template."
readme = "README.md"
license = "CC0-1.0"
keywords = ["cli", "project", "generator", "template", "skeleton", "prototype"]
categories = ["command-line-utilities", "development-tools"]
repository = "https://github.com/davidB/ffizer"
homepage = "https://github.com/davidB/ffizer"

[badges]
maintenance = { status = "experimental" }
appveyor = {repository = "davidB/ffizer", service = "github"}
travis-ci = {repository = "davidB/ffizer"}

[dependencies]
#fs_extra = "1.1.0"
#handlebars = "1.1.0"
#git2 = { version = "0.7.5", features = [], default-features = false }
#regex = "1.0.6"
#serde = "1.0"
#serde_yaml = "0.8"
# serde_json ="*"
dialoguer = "0.1.0"
failure = "0.1.3"
indicatif = "0.9.0"
slog = { version= "2.4.1", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2.3.0"
slog-term = "2.4.0"
structopt = "0.2.13"
walkdir = "2.2.6"

[dev-dependencies]
# assert_fs = "0.10"
# dir-diff = "0.3.1"
# rexpect = "0.3"
spectral = "0.6.0"
# tempfile = "3.0.4"

# duct for orchestrating multiple processes.
# rexpect for testing interactive programs.
# assert_fs for filesystem fixtures and assertions.
# dir-diff for testing file side-effects.
# tempfile for scratchpad directories.
# assert_cmd ?
# maybe switch to linefeed for interfaction, ui,...


[[bin]]
name = "ffizer"
path = "src/main.rs"
doc = false

[target.'cfg(all(unix, not(target_os = "redox")))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2"
winapi = "0.3"
