# see https://crates.io/crates/cargo-make

[env]
RUST_TEST_THREADS = "1"
CARGO_MAKE_TEST_COVERAGE_BINARY_FILTER = "cli-[a-z0-9]*$\\|makers-[a-z0-9]*$\\|${CARGO_MAKE_TEST_COVERAGE_DEFAULT_BINARY_FILTER}"
GITHUB_REPO="ffizer"
GITHUB_USER="ffizer"
# GITHUB_TOKEN=
DIST_NAME = "${CARGO_MAKE_CRATE_NAME}_${CARGO_MAKE_CRATE_VERSION}-${TARGET}"
DIST_EXT="tar.gz"
DIST_PATH="target/dist/${DIST_NAME}"

[env.windows]
DIST_PATH="target\\dist\\${DIST_NAME}"
DIST_EXT="zip"

[tasks.build-verbose]
# override
#args = ["build", "--verbose", "--all-features"]
args = ["build", "--all-features"]
#args = ["build", "--release", "--all-features"]

[tasks.test-verbose]
# override
#args = ["test", "--verbose", "--all-features"]
args = ["test"]
#args = ["test", "--release"]

[tasks.zip-release-ci-flow]
description = "Compiles the binary in release mode and zips it up"
category = "CI"
condition = { env_set = ["TARGET"] }
dependencies = [
  # "clean",
  "build-release-for-target",
  "zip-release-binary-for-target"
]

[tasks.build-release-for-target]
description = "Makes a release build for a given target"
condition = { env_set = [ "TARGET" ] }
command = "cargo"
args = [
  "build",
  "--release",
  "--all-features",
  "--target",
  "${TARGET}"
]

[tasks.zip-release-binary-for-target]
description = "Zips up the release binary, README, and license(s)"
category = "Publish"
condition = { env_set = [ "TARGET" ] }
# env = { "LIBZ_SYS_STATIC" = "1", "PKG_CONFIG_ALLOW_CROSS" = "1" }
script_runner = "@shell"
script = [
  "rm -Rf ${DIST_PATH}*",
  "mkdir -p ${DIST_PATH}",
  "cp target/${TARGET}/release/${CARGO_MAKE_CRATE_NAME} ${DIST_PATH}/",
  "strip ${DIST_PATH}/${CARGO_MAKE_CRATE_NAME}",
  # "cp README.md LICENSE* ${OUTPUT_NAME}/",
  # "zip -r ${OUTPUT_NAME}.zip ${OUTPUT_NAME}",
  "tar -czvf ${DIST_PATH}.${DIST_EXT} -C ${DIST_PATH} ."
]

[tasks.zip-release-binary-for-target.windows]
script_runner = "@shell"
script = [
  "setlocal enableextensions",
  "rm -Rf ${DIST_PATH}*",
  "md ${DIST_PATH}",
  "powershell copy-item -path target\\${TARGET}\\release\\${CARGO_MAKE_CRATE_NAME}.exe -destination ${DIST_PATH}",
  # "powershell copy-item -path README.md -destination ${OUTPUT_NAME}",
  # "powershell copy-item -path LICENSE -destination ${OUTPUT_NAME}",
  #"dir ${OUTPUT_NAME}",
  "powershell Compress-Archive -Path ${DIST_PATH}\\* -DestinationPath ${DIST_PATH}.${DIST_EXT} -CompressionLevel Optimal",
]

[tasks.update-changelog]
category="Publish"
install_crate = {crate_name="gitmoji-changelog", binary = "gitmoji-changelog", test_arg = "--help"}
script = [
  "rm -Rf CHANGELOG.md",
  "gitmoji-changelog -r x.y.z-dev -o CHANGELOG.md .",
]

# [tasks.pre-publish]
# dependencies = [
#   "update-changelog"
# ]

[tasks.publish]
command = "cargo"
args = ["release", "${@}"]


[tasks.github-upload]
condition = { env_set = [ "GITHUB_TOKEN", "GITHUB_REPO", "GITHUB_USER", "DIST_NAME", "DIST_PATH", "DIST_EXT"], channels = ["stable"] }
script= [
'''
curl "-H" "Authorization: token ${GITHUB_TOKEN}" \
    "-H" "Accept: application/vnd.github.manifold-preview" \
    "-H" "Content-Type: application/zip" \
    "--data-binary" "@${DIST_PATH}.${DIST_EXT}" \
    "https://uploads.github.com/repos/${GITHUB_REPO}/${GITHUB_USER}/releases/${CARGO_MAKE_CRATE_VERSION}/assets?name=${DIST_NAME}.${DIST_EXT}"
'''
]

[tasks.echo]
script=["echo ${CARGO_MAKE_PROFILE} : ${DIST_PATH}"]
