name: ffizer
version: git
summary: A tool to create (or update) files and folders from templates.
description: |
  ffizer is a files and folders initializer / generator.
  It creates or updates any kind (or part) of project from template(s)

grade: stable
confinement: devmode
base: core18

parts:
  ffizer:
    plugin: rust
    rust-channel: stable
    source: .
    build-packages: ["pkg-config", "libssl-dev"] # Required to prevent OpenSSL errors.

apps:
  ffizer:
    command: ffizer
