name: release-flow

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# on: release

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: ubuntu-latest
            target_platform: x86_64-unknown-linux-gnu
          - imageName: ubuntu-latest
            target_platform: x86_64-unknown-linux-musl
          - imageName: "macOS-latest"
            target_platform: x86_64-apple-darwin
          - imageName: "macOS-latest"
            target_platform: aarch64-apple-darwin
          - imageName: windows-latest
            target_platform:

    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          target: ${{ matrix.os.target_platform }}
          override: true
          profile: minimal
      - uses: davidB/rust-cargo-make@v1
      - name: Make zip-release-ci-flow
        run: cargo make zip-release-ci-flow
        env:
          TARGET: ${{ matrix.os.target_platform }}
          # DEVELOPER_DIR: "/Applications/Xcode_11.app/Contents/Developer"
      - name: Upload to gitHub release
        run: cargo make github-upload-flow
        env:
          TARGET: ${{ matrix.os.target_platform }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref }}
          # GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}
      # - name: Update snapcraft
      #   run: cargo make snapcraft-push
      #   env:
      #     SNAPCRAFT_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
      #     SNAPCRAFT_CHANNEL: beta
